/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SlugRouteRouteImport } from './routes/$slug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as PlatformSettingsRouteImport } from './routes/platform.settings'
import { Route as PlatformAdminRouteImport } from './routes/platform.admin'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as SlugLoginRouteImport } from './routes/$slug/login'
import { Route as SlugAccountRouteImport } from './routes/$slug/account'
import { Route as SlugAppRouteRouteImport } from './routes/$slug/app/route'
import { Route as SlugAppIndexRouteImport } from './routes/$slug/app/index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as SlugAppTeamRouteImport } from './routes/$slug/app/team'
import { Route as SlugAppSettingsRouteImport } from './routes/$slug/app/settings'
import { Route as SlugAppScanRouteImport } from './routes/$slug/app/scan'
import { Route as SlugAppReadersRouteImport } from './routes/$slug/app/readers'
import { Route as SlugAppLoansRouteImport } from './routes/$slug/app/loans'
import { Route as SlugAppDashboardRouteImport } from './routes/$slug/app/dashboard'
import { Route as SlugAppBooksRouteImport } from './routes/$slug/app/books'
import { Route as SlugActivateTokenRouteImport } from './routes/$slug/activate.$token'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as SlugAppReadersIdRouteImport } from './routes/$slug/app/readers.$id'

const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRouteRoute = SlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRouteRoute,
} as any)
const PlatformSettingsRoute = PlatformSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAdminRoute = PlatformAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PlatformRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SlugLoginRoute = SlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugAccountRoute = SlugAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugAppRouteRoute = SlugAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugAppIndexRoute = SlugAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugAppRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugAppTeamRoute = SlugAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SlugAppRouteRoute,
} as any)
const SlugAppSettingsRoute = SlugAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SlugAppRouteRoute,
} as any)
const SlugAppScanRoute = SlugAppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => SlugAppRouteRoute,
} as any)
const SlugAppReadersRoute = SlugAppReadersRouteImport.update({
  id: '/readers',
  path: '/readers',
  getParentRoute: () => SlugAppRouteRoute,
} as any)
const SlugAppLoansRoute = SlugAppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => SlugAppRouteRoute,
} as any)
const SlugAppDashboardRoute = SlugAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SlugAppRouteRoute,
} as any)
const SlugAppBooksRoute = SlugAppBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => SlugAppRouteRoute,
} as any)
const SlugActivateTokenRoute = SlugActivateTokenRouteImport.update({
  id: '/activate/$token',
  path: '/activate/$token',
  getParentRoute: () => SlugRouteRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const SlugAppReadersIdRoute = SlugAppReadersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SlugAppReadersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/platform': typeof PlatformRouteWithChildren
  '/$slug/app': typeof SlugAppRouteRouteWithChildren
  '/$slug/account': typeof SlugAccountRoute
  '/$slug/login': typeof SlugLoginRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/platform/admin': typeof PlatformAdminRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/$slug/': typeof SlugIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/$slug/activate/$token': typeof SlugActivateTokenRoute
  '/$slug/app/books': typeof SlugAppBooksRoute
  '/$slug/app/dashboard': typeof SlugAppDashboardRoute
  '/$slug/app/loans': typeof SlugAppLoansRoute
  '/$slug/app/readers': typeof SlugAppReadersRouteWithChildren
  '/$slug/app/scan': typeof SlugAppScanRoute
  '/$slug/app/settings': typeof SlugAppSettingsRoute
  '/$slug/app/team': typeof SlugAppTeamRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/$slug/app/': typeof SlugAppIndexRoute
  '/$slug/app/readers/$id': typeof SlugAppReadersIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/$slug/account': typeof SlugAccountRoute
  '/$slug/login': typeof SlugLoginRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/platform/admin': typeof PlatformAdminRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/$slug': typeof SlugIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/$slug/activate/$token': typeof SlugActivateTokenRoute
  '/$slug/app/books': typeof SlugAppBooksRoute
  '/$slug/app/dashboard': typeof SlugAppDashboardRoute
  '/$slug/app/loans': typeof SlugAppLoansRoute
  '/$slug/app/readers': typeof SlugAppReadersRouteWithChildren
  '/$slug/app/scan': typeof SlugAppScanRoute
  '/$slug/app/settings': typeof SlugAppSettingsRoute
  '/$slug/app/team': typeof SlugAppTeamRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/$slug/app': typeof SlugAppIndexRoute
  '/$slug/app/readers/$id': typeof SlugAppReadersIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/platform': typeof PlatformRouteWithChildren
  '/$slug/app': typeof SlugAppRouteRouteWithChildren
  '/$slug/account': typeof SlugAccountRoute
  '/$slug/login': typeof SlugLoginRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/platform/admin': typeof PlatformAdminRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/$slug/': typeof SlugIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/$slug/activate/$token': typeof SlugActivateTokenRoute
  '/$slug/app/books': typeof SlugAppBooksRoute
  '/$slug/app/dashboard': typeof SlugAppDashboardRoute
  '/$slug/app/loans': typeof SlugAppLoansRoute
  '/$slug/app/readers': typeof SlugAppReadersRouteWithChildren
  '/$slug/app/scan': typeof SlugAppScanRoute
  '/$slug/app/settings': typeof SlugAppSettingsRoute
  '/$slug/app/team': typeof SlugAppTeamRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/$slug/app/': typeof SlugAppIndexRoute
  '/$slug/app/readers/$id': typeof SlugAppReadersIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/accept-invite'
    | '/auth'
    | '/platform'
    | '/$slug/app'
    | '/$slug/account'
    | '/$slug/login'
    | '/onboarding'
    | '/email/unsubscribe'
    | '/platform/admin'
    | '/platform/settings'
    | '/$slug/'
    | '/platform/'
    | '/$slug/activate/$token'
    | '/$slug/app/books'
    | '/$slug/app/dashboard'
    | '/$slug/app/loans'
    | '/$slug/app/readers'
    | '/$slug/app/scan'
    | '/$slug/app/settings'
    | '/$slug/app/team'
    | '/lovable/email/suppression'
    | '/$slug/app/'
    | '/$slug/app/readers/$id'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/$slug/account'
    | '/$slug/login'
    | '/onboarding'
    | '/email/unsubscribe'
    | '/platform/admin'
    | '/platform/settings'
    | '/$slug'
    | '/platform'
    | '/$slug/activate/$token'
    | '/$slug/app/books'
    | '/$slug/app/dashboard'
    | '/$slug/app/loans'
    | '/$slug/app/readers'
    | '/$slug/app/scan'
    | '/$slug/app/settings'
    | '/$slug/app/team'
    | '/lovable/email/suppression'
    | '/$slug/app'
    | '/$slug/app/readers/$id'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_authenticated'
    | '/accept-invite'
    | '/auth'
    | '/platform'
    | '/$slug/app'
    | '/$slug/account'
    | '/$slug/login'
    | '/_authenticated/onboarding'
    | '/email/unsubscribe'
    | '/platform/admin'
    | '/platform/settings'
    | '/$slug/'
    | '/platform/'
    | '/$slug/activate/$token'
    | '/$slug/app/books'
    | '/$slug/app/dashboard'
    | '/$slug/app/loans'
    | '/$slug/app/readers'
    | '/$slug/app/scan'
    | '/$slug/app/settings'
    | '/$slug/app/team'
    | '/lovable/email/suppression'
    | '/$slug/app/'
    | '/$slug/app/readers/$id'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRouteRoute: typeof SlugRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/platform/settings': {
      id: '/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof PlatformSettingsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/admin': {
      id: '/platform/admin'
      path: '/admin'
      fullPath: '/platform/admin'
      preLoaderRoute: typeof PlatformAdminRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$slug/login': {
      id: '/$slug/login'
      path: '/login'
      fullPath: '/$slug/login'
      preLoaderRoute: typeof SlugLoginRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/account': {
      id: '/$slug/account'
      path: '/account'
      fullPath: '/$slug/account'
      preLoaderRoute: typeof SlugAccountRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/app': {
      id: '/$slug/app'
      path: '/app'
      fullPath: '/$slug/app'
      preLoaderRoute: typeof SlugAppRouteRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/app/': {
      id: '/$slug/app/'
      path: '/'
      fullPath: '/$slug/app/'
      preLoaderRoute: typeof SlugAppIndexRouteImport
      parentRoute: typeof SlugAppRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/app/team': {
      id: '/$slug/app/team'
      path: '/team'
      fullPath: '/$slug/app/team'
      preLoaderRoute: typeof SlugAppTeamRouteImport
      parentRoute: typeof SlugAppRouteRoute
    }
    '/$slug/app/settings': {
      id: '/$slug/app/settings'
      path: '/settings'
      fullPath: '/$slug/app/settings'
      preLoaderRoute: typeof SlugAppSettingsRouteImport
      parentRoute: typeof SlugAppRouteRoute
    }
    '/$slug/app/scan': {
      id: '/$slug/app/scan'
      path: '/scan'
      fullPath: '/$slug/app/scan'
      preLoaderRoute: typeof SlugAppScanRouteImport
      parentRoute: typeof SlugAppRouteRoute
    }
    '/$slug/app/readers': {
      id: '/$slug/app/readers'
      path: '/readers'
      fullPath: '/$slug/app/readers'
      preLoaderRoute: typeof SlugAppReadersRouteImport
      parentRoute: typeof SlugAppRouteRoute
    }
    '/$slug/app/loans': {
      id: '/$slug/app/loans'
      path: '/loans'
      fullPath: '/$slug/app/loans'
      preLoaderRoute: typeof SlugAppLoansRouteImport
      parentRoute: typeof SlugAppRouteRoute
    }
    '/$slug/app/dashboard': {
      id: '/$slug/app/dashboard'
      path: '/dashboard'
      fullPath: '/$slug/app/dashboard'
      preLoaderRoute: typeof SlugAppDashboardRouteImport
      parentRoute: typeof SlugAppRouteRoute
    }
    '/$slug/app/books': {
      id: '/$slug/app/books'
      path: '/books'
      fullPath: '/$slug/app/books'
      preLoaderRoute: typeof SlugAppBooksRouteImport
      parentRoute: typeof SlugAppRouteRoute
    }
    '/$slug/activate/$token': {
      id: '/$slug/activate/$token'
      path: '/activate/$token'
      fullPath: '/$slug/activate/$token'
      preLoaderRoute: typeof SlugActivateTokenRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/app/readers/$id': {
      id: '/$slug/app/readers/$id'
      path: '/$id'
      fullPath: '/$slug/app/readers/$id'
      preLoaderRoute: typeof SlugAppReadersIdRouteImport
      parentRoute: typeof SlugAppReadersRoute
    }
  }
}

interface SlugAppReadersRouteChildren {
  SlugAppReadersIdRoute: typeof SlugAppReadersIdRoute
}

const SlugAppReadersRouteChildren: SlugAppReadersRouteChildren = {
  SlugAppReadersIdRoute: SlugAppReadersIdRoute,
}

const SlugAppReadersRouteWithChildren = SlugAppReadersRoute._addFileChildren(
  SlugAppReadersRouteChildren,
)

interface SlugAppRouteRouteChildren {
  SlugAppBooksRoute: typeof SlugAppBooksRoute
  SlugAppDashboardRoute: typeof SlugAppDashboardRoute
  SlugAppLoansRoute: typeof SlugAppLoansRoute
  SlugAppReadersRoute: typeof SlugAppReadersRouteWithChildren
  SlugAppScanRoute: typeof SlugAppScanRoute
  SlugAppSettingsRoute: typeof SlugAppSettingsRoute
  SlugAppTeamRoute: typeof SlugAppTeamRoute
  SlugAppIndexRoute: typeof SlugAppIndexRoute
}

const SlugAppRouteRouteChildren: SlugAppRouteRouteChildren = {
  SlugAppBooksRoute: SlugAppBooksRoute,
  SlugAppDashboardRoute: SlugAppDashboardRoute,
  SlugAppLoansRoute: SlugAppLoansRoute,
  SlugAppReadersRoute: SlugAppReadersRouteWithChildren,
  SlugAppScanRoute: SlugAppScanRoute,
  SlugAppSettingsRoute: SlugAppSettingsRoute,
  SlugAppTeamRoute: SlugAppTeamRoute,
  SlugAppIndexRoute: SlugAppIndexRoute,
}

const SlugAppRouteRouteWithChildren = SlugAppRouteRoute._addFileChildren(
  SlugAppRouteRouteChildren,
)

interface SlugRouteRouteChildren {
  SlugAppRouteRoute: typeof SlugAppRouteRouteWithChildren
  SlugAccountRoute: typeof SlugAccountRoute
  SlugLoginRoute: typeof SlugLoginRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugActivateTokenRoute: typeof SlugActivateTokenRoute
}

const SlugRouteRouteChildren: SlugRouteRouteChildren = {
  SlugAppRouteRoute: SlugAppRouteRouteWithChildren,
  SlugAccountRoute: SlugAccountRoute,
  SlugLoginRoute: SlugLoginRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugActivateTokenRoute: SlugActivateTokenRoute,
}

const SlugRouteRouteWithChildren = SlugRouteRoute._addFileChildren(
  SlugRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PlatformRouteChildren {
  PlatformAdminRoute: typeof PlatformAdminRoute
  PlatformSettingsRoute: typeof PlatformSettingsRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAdminRoute: PlatformAdminRoute,
  PlatformSettingsRoute: PlatformSettingsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRouteRoute: SlugRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
  PlatformRoute: PlatformRouteWithChildren,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
